#!/usr/bin/env node
// Shared document fixtures (testing.md §3: built, never hand-copied): fixtures/docs/*.flux.json
// from the @fluxion/schema/testing builders, in canonical form.
//   gen.mjs            write every fixture (and delete stale ones)
//   gen.mjs --check    exit 1 when a fixture is missing, stale or not generated here
// Names say how a fixture behaves: `invalid-<code>` fails validation with FLX_<CODE>, every other
// fixture parses with no error (packages/schema: "fixtures/docs behave as named").
// Reads the built package (dist): run `pnpm run build` first.
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const ROOT = join(import.meta.dirname, '..', '..');
const DIR = join(ROOT, 'fixtures', 'docs');
const DIST = join(ROOT, 'packages', 'schema', 'dist');
if (!existsSync(join(DIST, 'testing', 'index.js'))) {
  console.error('fixtures: packages/schema/dist is missing; run `pnpm run build` first');
  process.exit(1);
}
const { serializeDocument } = await import(pathToFileURL(join(DIST, 'index.js')).href);
const { documentBuilder } = await import(pathToFileURL(join(DIST, 'testing', 'index.js')).href);

function twoRectsLine(title) {
  const b = documentBuilder({ title, seed: 2 });
  const s = b.screen({ name: 'Main' });
  const a = b.rect(s, { x: 120, y: 200, label: 'Client', slug: 'client' });
  const c = b.rect(s, { x: 520, y: 200, label: 'Server', slug: 'server' });
  const line = b.connect(a, c);
  return { doc: b.build(), screen: s, rect: a, line };
}

/** Put `patch` into record `id` of `doc` (a copy). */
const patched = (doc, id, patch) => ({ ...doc, records: { ...doc.records, [id]: { ...doc.records[id], ...patch } } });

const FIXTURES = {
  minimal: () => {
    const b = documentBuilder({ title: 'Minimal', seed: 1 });
    b.screen({ name: 'Main' });
    return b.build();
  },
  'two-rects-line': () => twoRectsLine('Two rects and a line').doc,
  // a plugin element kind, a core kind from a newer version (FLX_KIND_UNKNOWN warning, M2 final F7)
  // and unknown fields are all kept verbatim (FR-DOC-005)
  'unknown-kind': () => {
    const { doc, screen } = twoRectsLine('Unknown kind');
    const gauge = {
      id: 'GaugeGaugeGauge1',
      type: 'element',
      screenId: screen,
      index: 'a9',
      kind: 'acme:gauge',
      transform: { x: 120, y: 400, w: 160, h: 80 },
      props: { value: 0.42 },
      future: { x: 1 },
    };
    const hologram = {
      id: 'HologramHologram',
      type: 'element',
      screenId: screen,
      index: 'aA',
      kind: 'hologram',
      transform: { x: 320, y: 400, w: 160, h: 80 },
      depth: 3,
    };
    return { ...doc, records: { ...doc.records, [gauge.id]: gauge, [hologram.id]: hologram } };
  },
  // an element on a screen that does not exist
  'invalid-ref-missing': () => {
    const { doc, rect } = twoRectsLine('Missing screen');
    return patched(doc, rect, { screenId: 'NoSuchScreen0000' });
  },
  // a record that does not match its schema
  'invalid-schema-invalid': () => {
    const { doc, rect } = twoRectsLine('Bad transform');
    return patched(doc, rect, { transform: { x: 0, y: 0, w: 'wide', h: 80 } });
  },
};

const wanted = new Map(Object.entries(FIXTURES).map(([name, build]) => [`${name}.flux.json`, serializeDocument(build())]));
const present = existsSync(DIR) ? readdirSync(DIR).filter((f) => f.endsWith('.flux.json')) : [];

if (process.argv.includes('--check')) {
  const problems = [
    ...[...wanted].filter(([f, text]) => !present.includes(f) || readFileSync(join(DIR, f), 'utf8') !== text).map(([f]) => `${f} is missing or stale`),
    ...present.filter((f) => !wanted.has(f)).map((f) => `${f} is not generated by scripts/fixtures/gen.mjs`),
  ];
  for (const p of problems) console.error(`fixtures: ${p}`);
  if (problems.length) console.error('Run `node scripts/fixtures/gen.mjs` and commit the result.');
  else console.log(`fixtures: ${wanted.size} fixture(s) current`);
  process.exit(problems.length ? 1 : 0);
}

mkdirSync(DIR, { recursive: true });
for (const f of present.filter((f) => !wanted.has(f))) rmSync(join(DIR, f));
for (const [f, text] of wanted) writeFileSync(join(DIR, f), text);
console.log(`fixtures: wrote ${wanted.size} fixture(s) to fixtures/docs`);
