// FR-DSL-006 (M12.36): the FluxScript diagnostics page is generated from DSL_CODES, lists every code with its severity, and is current.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it } from 'node:test';
import { PAGE, render } from '../../scripts/docs/fluxscript-diagnostics.mjs';
import { REPO } from './helpers.mjs';

describe('FluxScript diagnostics page (FR-DSL-006)', () => {
  it('FR-DSL-006: the page lists each code with its severity, sorted, and escapes a pipe in a description', () => {
    const text = render({ FLX_B: { severity: 'warning', description: 'b | c' }, FLX_A: { severity: 'error', description: 'a' } });
    const rows = text.split('\n').filter((l) => l.startsWith('| `'));
    assert.deepEqual(rows, ['| `FLX_A` | error | a |', '| `FLX_B` | warning | b \\| c |']);
    assert.match(text, /GENERATED by scripts\/docs\/fluxscript-diagnostics\.mjs/);
  });

  it('FR-DSL-006: the written page is what the registry generates and names every code in codes.ts', () => {
    const check = spawnSync(process.execPath, [join(REPO, 'scripts/docs/fluxscript-diagnostics.mjs'), '--check'], { encoding: 'utf8' });
    assert.equal(check.status, 0, check.stderr);
    const codes = [...readFileSync(join(REPO, 'packages/dsl/src/diagnostics/codes.ts'), 'utf8').matchAll(/^ {2}(FLX_[A-Z_]+): \{/gm)].map((m) => m[1]);
    assert.ok(codes.length >= 10);
    const page = readFileSync(PAGE, 'utf8');
    for (const code of codes) assert.match(page, new RegExp(`^\\| \`${code}\` \\| (error|warning|info) \\|`, 'm'), code);
  });
});
