#!/usr/bin/env node
// Generate Claude Code skill adapters from canonical skills.
//   node scripts/harness/sync-skills.mjs          write .claude/skills/<name>/SKILL.md
//   node scripts/harness/sync-skills.mjs --check  exit 1 if adapters are missing/stale/orphaned
//
// Canonical procedures live in .agents/skills (Codex reads them natively). Claude reads
// .claude/skills, so each adapter repeats name + description (+ Claude-only keys from
// skill-adapters.json) and points to the canonical body. Copies, not symlinks: Windows symlinks
// need Developer Mode.
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { frontMatter, repoPath } from '../gates/lib.mjs';

const SRC = repoPath('.agents', 'skills');
const DST = repoPath('.claude', 'skills');
const extra = JSON.parse(readFileSync(repoPath('scripts', 'harness', 'skill-adapters.json'), 'utf8'));
const check = process.argv.includes('--check');

const skills = readdirSync(SRC, { withFileTypes: true })
  .filter((d) => d.isDirectory() && existsSync(join(SRC, d.name, 'SKILL.md')))
  .map((d) => d.name)
  .sort();

function adapter(name) {
  const fm = frontMatter(readFileSync(join(SRC, name, 'SKILL.md'), 'utf8'));
  if (!fm) throw new Error(`${name}: SKILL.md has no front matter`);
  const keys = { name: fm.data.name, description: fm.data.description, ...(extra[name] ?? {}) };
  delete keys.$comment;
  const yaml = Object.entries(keys)
    .map(([k, v]) => `${k}: ${v}`)
    .join('\n');
  return `---\n${yaml}\n---\n\n<!-- GENERATED by scripts/harness/sync-skills.mjs from .agents/skills/${name}/SKILL.md — do not edit -->\n\nRead \`.agents/skills/${name}/SKILL.md\` now and follow it exactly. Arguments given with this command (if any) are its input.\n`;
}

const problems = [];
for (const name of skills) {
  const want = adapter(name);
  const file = join(DST, name, 'SKILL.md');
  const have = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (have === want) continue;
  if (check) problems.push(`${have === null ? 'missing' : 'stale'} adapter: .claude/skills/${name}/SKILL.md`);
  else {
    mkdirSync(join(DST, name), { recursive: true });
    writeFileSync(file, want);
    console.log(`wrote .claude/skills/${name}/SKILL.md`);
  }
}
if (existsSync(DST)) {
  for (const d of readdirSync(DST, { withFileTypes: true })) {
    if (!d.isDirectory() || skills.includes(d.name)) continue;
    if (check) problems.push(`orphan adapter: .claude/skills/${d.name}`);
    else {
      rmSync(join(DST, d.name), { recursive: true });
      console.log(`removed orphan .claude/skills/${d.name}`);
    }
  }
}
if (problems.length) {
  for (const p of problems) console.error(p);
  console.error('Run: node scripts/harness/sync-skills.mjs');
  process.exit(1);
}
if (check) console.log(`skills in sync (${skills.length})`);
